### PR TITLE
Code review guestbook

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@codyhoag, the main changes are in the last two commits. Here's the diff: 60e3c8c...c015895. The other changes are basically source formatting, config changes, and a minor bug fix. Let me know if you have any questions or want me to change anything.

**Comment by stiemannkj1** [comment]
cc @ngriffin7a

**Comment by stiemannkj1** [comment]
@codyhoag webapp version is here: https://github.com/stiemannkj1/jsf-app-dev/tree/webapp. You can do a diff between branches to see the changes need to be made to turn the webapp into a portlet:

```
git diff webapp code-review-guestbook
```

For your doc explaining the process of migrating to Liferay I recommend you tell people to generate a new JSF portlet using our archetypes and copy their code to it since it will generate most of the boilerplate config.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Do you have time to do a code review and make some improvements? For example I see some out-of-the-ordinary EL expressions passing `facesContext` as an EL parameter in https://github.com/stiemannkj1/jsf-app-dev/blob/webapp/jsf-guestbook-workspace/wars/guestbook-jsf-portlet/src/main/webapp/views/master.xhtml

**Comment by stiemannkj1** [comment]
@ngriffin7a, that's part of my code review. I prefer to pass the `FacesContext` because it makes it easier to unit test each bean.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Is it possible to perform unit testing by calling FacesContext.getCurrentInstance() in the Java source?

**Comment by stiemannkj1** [comment]
@ngriffin7a, perhaps there's a way to do it with `FacesContext.getCurrentInstance()`, but I'm not sure how and it would definitely be more complicated than simply mocking the `FacesContext`.

There are also performance implications from accessing a thread local, so passing is recommended by [Arjan Tims](https://stackoverflow.com/questions/13536902/jsf-pass-facescontext-or-use-getcurrentinstance#13540262) and [JSF 2.0 Expert Group member Roger Keays](http://content.jsfcentral.com/c/journal_articles/view_article_content?groupId=35702&articleId=58321&version=1.7#.XGSGZKxKhhE).

**Comment by codyhoag** [comment]
@stiemannkj1 this is great! Thanks for the speedy review and webapp creation. I'll definitely recommend the archetype generation when migrating to Liferay.

Do you mind giving me a general explanation for each class and your thought process for splitting them up the way they are (`EntryBacking`, `GuestbookBacking`, `EntryDTO`, and `GuestbookManager`)? I think having a general background for the anatomy will help when talking about it.

After a brief look in the source code, I don't have any initial complaints. But I'll likely have some questions as I progress through the documentation process. I'll keep you in the loop.

Thanks again!

**Comment by stiemannkj1** [comment]
@codyhoag, just pushed https://github.com/codyhoag/jsf-app-dev/pull/1/commits/3c4acab59c653266c1cd8601a3fa8beca2f8dbeb to add class-level JavaDocs. Please let me know if they answer your questions.

I also had to force push my `webapp` branch so you'll need to delete whatever version you have locally and re-fetch it (if you already fetched it).

**Comment by codyhoag** [comment]
Thanks @stiemannkj1; very helpful!

**Comment by codyhoag** [comment]
Merged both the JSF webapp and Liferay JSF app projects and pushed to my origin as branches `webapp-jsf-guestbook-final` and `liferay-jsf-guestbook-final`. We'll finalize the Liferay-specfic code when the thin WAR stuff is ready. Thanks!

**Pull request closed without merging**
